language: generic 
sudo: require
services:
  - docker

before_install:
  - docker build -t bigjack213/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bigjack213/docker-react npm run test